[project]
name = "noaa_qpf"
version = "0.1.0"
description = "NOAA Quantitative Precipitation Forecasts"
readme = "README.md"
authors = [
    { name = "Colton Loftus", email = "70598503+C-Loftus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
