server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5005
  url: ${PYGEOAPI_URL:-http://localhost:5005} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  templates:
    path: /opt/pygeoapi/pygeoapi-deployment/templates
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Western Water Datahub
    description: The Western Water Datahub is an implementation of OGC API - EDR supported by the United States Bureau of Reclamation.
    keywords:
      - usbr
      - wwdh
      - iow
    keywords_type: theme
    terms_of_service: https://opensource.org/license/MIT
    url: https://github.com/internetofwater/WWDH
  license:
    name: MIT License
    url: https://opensource.org/license/MIT
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/WWDH
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://cgsearth.org
    role: pointOfContact
    name: Benjamin Webb

resources:
  rise-edr:
    type: collection
    title: Reclamation Information Sharing Environment (RISE)
    description: United States Bureau of Reclamation Information Sharing Environment EDR
    keywords:
      - EDR
      - RISE
      - USBR
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-123.60518, 28.4667, -95.875, 48.8283]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: rise.rise_edr.RiseEDRProvider
        data: https://data.usbr.gov/
        title_field: name
      - type: feature
        name: rise.rise.RiseProvider
        data: https://data.usbr.gov/
        title_field: name

  snotel-edr:
    type: collection
    title: Snow Telemetry Network (SNOTEL)
    description: United States Department of Agriculture Snow Telemetry Network EDR
    keywords:
      - EDR
      - SNOTEL
      - NRCS
      - USDA
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://www.nrcs.usda.gov/wps/portal/wcc/home/aboutUs/monitoringPrograms/automatedSnowMonitoring/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-164.92472, 32.92342, -103.78758, 70.28062]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: snotel.snotel_edr.SnotelEDRProvider
        data: https://wcc.sc.egov.usda.gov/
        title_field: name
      - type: feature
        name: snotel.snotel.SnotelProvider
        data: https://wcc.sc.egov.usda.gov/
        title_field: name

  usgs-sta:
    type: collection
    title: United States Geologic Survey SensorThings API
    description: United States Geologic Survey SensorThings API EDR
    keywords:
      - EDR
      - SensorThings
      - USGS
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://labs.waterdata.usgs.gov
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: SensorThingsEDR
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
      - type: feature
        name: SensorThings
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
        entity: Things
        title_field: name

  awdb-forecasts-edr:
    type: collection
    title: Air and Water Database (AWDB) Forecasts
    description: United States Department of Agriculture Air and Water Database Forecasts EDR
    keywords:
      - open data
    extents:
      spatial:
        bbox: [-171.791110603, 18.91619, -66.96466, 71.3577635769]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: awdb_forecasts.awdb_forecasts_edr.AwdbForecastsEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - type: feature
        name: awdb_forecasts.awdb_forecasts.AwdbForecastsProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        title_field: name


  usace-edr:
    type: collection
    title: US Army Corps of Engineers (USACE) EDR 
    description: US Army Corps of Engineers EDR
    keywords:
      - open data
    extents:
      spatial:
        bbox: [-171.791110603, 18.91619, -66.96466, 71.3577635769]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: usace.usace_edr.USACEEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - type: feature
        name: usace.usace.USACEProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        entity: Observation
        title_field: name


  noaa-qpf-24-hour-day-1:
    type: collection
    title: NOAA QPF 24 Hours Day 1
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 1
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/1
        id_field: objectid
        time_field: issue_time

  noaa-qpf-24-hour-day-2:
    type: collection
    title: NOAA QPF 24 Hours Day 2
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 2
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/2
        id_field: objectid
        time_field: issue_time

  noaa-qpf-24-hour-day-3:
    type: collection
    title: NOAA QPF 24 Hours Day 3
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 3
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/3
        id_field: objectid
        time_field: issue_time

  noaa-qpf-48-hour-day-4:
    type: collection
    title: NOAA QPF 48 Hours Day 4-5
    description: NOAA Quantitative Precipitation Forecast (QPF) 48 Hours Day 4-5
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/4
        id_field: objectid
        time_field: issue_time

  noaa-qpf-48-hour-day-6-7:
    type: collection
    title: NOAA QPF 48 Hour Day 6-7
    description: NOAA Quantitative Precipitation Forecast (QPF) 48 Hour Day 6-7
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/5
        id_field: objectid
        time_field: issue_time

  noaa-qpf-cumulative-6-hours-day-1:
    type: collection
    title: NOAA QPF Cumulative 6 Hours Day 1
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 6 Hours Day 1
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/7
        id_field: objectid
        time_field: issue_time

  noaa-qpf-cumulative-48-hours-day-1-2:
    type: collection
    title: NOAA QPF Cumulative 48 Hours Day 1-2
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 48 Hours Day 1-2
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/8
        id_field: objectid
        time_field: issue_time

  noaa-qpf-cumulative-72-hours-day-1-3:
    type: collection
    title: NOAA QPF Cumulative 72 Hours Day 1-3
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 72 Hours Day 1-3
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/9
        id_field: objectid
        time_field: issue_time

  noaa-qpf-cumulative-120-hours-day-1-5:
    type: collection
    title: NOAA QPF Cumulative 120 Hours Day 1-5
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 120 Hours Day 1-5
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/10
        id_field: objectid
        time_field: issue_time

  noaa-qpf-cumulative-168-hours-day-1-7:
    type: collection
    title: NOAA QPF Cumulative 168 Hours Day 1-7
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 168 Hours Day 1-7
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/11
        id_field: objectid
        time_field: issue_time

  noaa-day-1-prob-at-least-4-inches-snow:
    type: collection
    title: NOAA Day 1 Prob At Least 4 Inches Snow
    description: NOAA Day 1 Prob At Least 4 Inches Snow
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/1
        id_field: objectid
        time_field: issue_time

  noaa-day-1-prob-at-least-8-inches-snow:
    type: collection
    title: NOAA Day 1 Prob At Least 8 Inches Snow
    description: NOAA Day 1 Prob At Least 8 Inches Snow
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/2
        id_field: objectid
        time_field: issue_time

  noaa-day-1-prob-at-least-12-inches-snow:
    type: collection
    title: NOAA Day 1 Prob At Least 12 Inches Snow
    description: NOAA Day 1 Prob At Least 12 Inches Snow
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/3
        id_field: objectid
        time_field: issue_time

  noaa-day-1-prob-icing-at-least-.25-inches:
    type: collection
    title: NOAA Day 1 Prob Icing At Least .25 Inches
    description: NOAA Day 1 Prob Icing At Least .25 Inches
    keywords: [NOAA, QPF]
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/4
        id_field: objectid
        time_field: issue_time

  nohrsc-swe:
    type: collection
    title: NOAA NOHRSC Snow Water Forecast
    description: NOAA NOHRSC Snow Water Forecast
    keywords:
      - nohrsc
      - snow water equivalent
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://www.nohrsc.noaa.gov/nsa/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-130.516667, 24.1, -62.25273100000001, 58.240301]
        crs: http://www.opengis.net/def/crs/EPSG/0/4269
    providers:
      - type: map
        name: WMSFacade
        data: https://mapservices.weather.noaa.gov/raster/services/snow/NOHRSC_Snow_Analysis/MapServer/WMSServer
        options:
          layer: 1
          style: default
          projection: 4269
        format:
          name: png
          mimetype: image/png

  nohrsc-sd:
    type: collection
    title: NOAA NOHRSC Snow Depth Forecast
    description: NOAA NOHRSC Snow Depth Forecast
    keywords:
      - nohrsc
      - snow depth
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://www.nohrsc.noaa.gov/nsa/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-130.516667, 24.1, -62.25273100000001, 58.240301]
        crs: http://www.opengis.net/def/crs/EPSG/0/4269
    providers:
      - type: map
        name: WMSFacade
        data: https://mapservices.weather.noaa.gov/raster/services/snow/NOHRSC_Snow_Analysis/MapServer/WMSServer
        options:
          layer: 5
          style: default
          projection: 4269
        format:
          name: png
          mimetype: image/png

  usgs-prism:
    type: collection
    title: Parameter-elevation Regressions on Independent Slopes Model (PRISM)
    description: PRISM Monthly Climate Data for the Continental United States
    keywords:
      - temperature
      - precipitation
    extents:
      spatial:
        bbox: [-125.020836, 24.104166, -66.520836, 49.9375]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 1895-01-01T00:00:00Z
        end: 2020-12-01T00:00:00Z
        trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
        values: ["R1500/1895-01-01T00:00:00Z/P1M"]
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://cida.usgs.gov/thredds/catalog.html?dataset=cida.usgs.gov/prism_v2
        hreflang: en-US
    providers:
      - type: edr
        name: xarray-edr
        data: s3://mdmf/gdp/PRISM_v2.zarr
        format:
          name: zarr
          mimetype: application/zip
        options:
          s3:
            anon: true
            requester_pays: false
            client_kwargs:
              endpoint_url: https://usgs.osn.mghpcc.org/

  # noaa-nwm:
  #   type: collection
  #   title: NOAA National Water Model CONUS Retrospective Dataset
  #   description: NOAA National Water Model CONUS Retrospective Dataset
  #   keywords:
  #     - national water model
  #     - agriculture
  #   extents:
  #     spatial:
  #       bbox: [-125.020836, 24.104166, -66.520836, 49.9375]
  #       crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
  #   links:
  #     - type: text/html
  #       rel: canonical
  #       title: information
  #       href: https://registry.opendata.aws/nwm-archive/
  #       hreflang: en-US
  #   providers:
  #     - type: edr
  #       name: xarray-edr
  #       data: s3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/chrtout.zarr
  #       x_field: longitude
  #       y_field: latitude
  #       format:
  #         name: zarr
  #         mimetype: application/zip
  #       options:
  #         s3:
  #           anon: true
