# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Docker Compose Build Test

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: |
          docker compose pull || true  # Pull images if available, but don't fail if they aren't
          docker compose build --no-cache

      - name: Verify services can start
        run: |
          docker compose up -d
          sleep 10  # Give containers some time to initialize
          docker compose ps

      - name: Stop and clean up
        run: |
          docker compose down
