# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

[project]
name = "awdb-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Colton Loftus", email = "70598503+C-Loftus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
