#=================================================================
#
# Authors: Benjamin Webb <bwebb@lincolninst.edu
#
# Copyright (c) 2025 Lincoln Institute of Land Policy
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5005
  url: ${PYGEOAPI_URL:-http://localhost:5005} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  templates:
    path: /opt/pygeoapi/templates
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: DEBUG
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: US Bureau of Reclamation Interoperable Data Hub
    description: US Bureau of Reclamation Interoperable Data Hub
    keywords:
      - usbr
      - iodh
      - iow
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/IODH
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/IODH
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://cgsearth.org
    role: pointOfContact
    name: Benjamin Webb

resources:   
  # usgs-prism:
  #   type: collection
  #   title: Parameter-elevation Regressions on Independent Slopes Model (PRISM)
  #   description: PRISM Monthly Climate Data for the Continental United States
  #   keywords:
  #     - temperature
  #     - precipitation
  #   extents:
  #     spatial:
  #       bbox: [-125.020836, 24.104166, -66.520836, 49.9375]
  #       crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
  #     temporal:
  #       begin: 1895-01-01T00:00:00Z
  #       end: 2020-12-01T00:00:00Z
  #       trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
  #       values: ['R1500/1895-01-01T00:00:00Z/P1M']
  #   links:
  #     - type: text/html
  #       rel: canonical
  #       title: information
  #       href: https://cida.usgs.gov/thredds/catalog.html?dataset=cida.usgs.gov/prism_v2
  #       hreflang: en-US
  #   providers:
  #     - type: edr
  #       name: xarray-edr
  #       data: s3://mdmf/gdp/PRISM_v2.zarr
  #       format:
  #         name: zarr
  #         mimetype: application/zip
  #       options:
  #         s3:
  #           anon: true
  #           requester_pays: false
  #           client_kwargs:
  #             endpoint_url: https://usgs.osn.mghpcc.org/

  rise-edr:
    type: collection
    title: Reclamation Information Sharing Environment
    description: United States Bureau of Reclamation Information Sharing Environment EDR
    keywords:
      - EDR
      - RISE
      - USBR
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-123.60518, 28.4667, -95.875, 48.8283]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: rise.rise_edr.RiseEDRProvider
        data: https://data.usbr.gov/
        title_field: name
      - type: feature
        name: rise.rise.RiseProvider
        data: https://data.usbr.gov/
        title_field: name

  # usgs-sta:
  #   type: collection
  #   title: United States Geologic Survey SensorThings API
  #   description: United States Geological Survey SensorThings API EDR
  #   keywords:
  #     - EDR
  #     - SensorThings
  #     - USGS
  #   links:
  #     - type: application/html
  #       rel: canonical
  #       title: data source
  #       href: https://labs.waterdata.usgs.gov
  #       hreflang: en-US
  #   extents:
  #     spatial:
  #       bbox: [-170, 15, -51, 72]
  #       crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
  #   providers:
  #     - type: edr
  #       name: SensorThingsEDR
  #       data: https://labs.waterdata.usgs.gov/sta/v1.1/
  #     - type: feature
  #       name: SensorThings
  #       data: https://labs.waterdata.usgs.gov/sta/v1.1/
  #       entity: Things
  #       title_field: name


  # noaa-nwm:
  #   type: collection
  #   title: NOAA National Water Model CONUS Retrospective Dataset
  #   description: NOAA National Water Model CONUS Retrospective Dataset
  #   keywords:
  #     - national water model
  #     - agriculture
  #   extents:
  #     spatial:
  #       bbox: [-125.020836, 24.104166, -66.520836, 49.9375]
  #       crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
  #   links:
  #     - type: text/html
  #       rel: canonical
  #       title: information
  #       href: https://registry.opendata.aws/nwm-archive/
  #       hreflang: en-US
  #   providers:
  #     - type: edr
  #       name: xarray-edr
  #       data: s3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/chrtout.zarr
  #       x_field: longitude
  #       y_field: latitude
  #       format:
  #         name: zarr
  #         mimetype: application/zip
  #       options:
  #         s3:
  #           anon: true
